# Generated by Django 4.2.2 on 2023-07-22 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swimeeter_auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='data_entry_information',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='host',
            name='motion_safe',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
