# Generated by Django 4.2.2 on 2023-07-21 20:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import swimeeter_api_app.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stroke', models.CharField(max_length=255)),
                ('distance', models.PositiveSmallIntegerField()),
                ('is_relay', models.BooleanField()),
                ('swimmers_per_entry', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('stage', models.CharField(max_length=255)),
                ('competing_gender', models.CharField(max_length=255)),
                ('competing_max_age', models.PositiveSmallIntegerField(null=True)),
                ('competing_min_age', models.PositiveSmallIntegerField(null=True)),
                ('order_in_session', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('total_heats', models.PositiveSmallIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(1)])),
                ('begin_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('is_public', models.BooleanField()),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(1)])),
                ('street_address', models.CharField(default='', max_length=255, validators=[django.core.validators.MinLengthValidator(1)])),
                ('city', models.CharField(default='', max_length=255, validators=[django.core.validators.MinLengthValidator(1)])),
                ('state', models.CharField(default='', max_length=255, validators=[django.core.validators.MinLengthValidator(1)])),
                ('country', models.CharField(default='', max_length=255, validators=[django.core.validators.MinLengthValidator(1)])),
                ('zipcode', models.CharField(default='', max_length=255, validators=[django.core.validators.MinLengthValidator(1)])),
                ('lanes', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(3)])),
                ('side_length', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('measure_unit', models.CharField(max_length=255)),
                ('meet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pools', to='swimeeter_api_app.meet')),
            ],
        ),
        migrations.CreateModel(
            name='Relay_assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_in_relay', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('seed_relay_split', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Swimmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, validators=[swimeeter_api_app.validators.swimmer_fl_name_validator, django.core.validators.MinLengthValidator(1)])),
                ('last_name', models.CharField(max_length=255, validators=[swimeeter_api_app.validators.swimmer_fl_name_validator, django.core.validators.MinLengthValidator(1)])),
                ('prefix', models.CharField(default='', max_length=255, validators=[swimeeter_api_app.validators.swimmer_ps_fix_validator])),
                ('suffix', models.CharField(default='', max_length=255, validators=[swimeeter_api_app.validators.swimmer_ps_fix_validator])),
                ('middle_initials', models.CharField(default='', max_length=255, validators=[swimeeter_api_app.validators.swimmer_mi_validator])),
                ('age', models.PositiveSmallIntegerField()),
                ('gender', models.CharField(max_length=255)),
                ('team_name', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(1)])),
                ('team_acronym', models.CharField(max_length=255, validators=[swimeeter_api_app.validators.team_acronym_validator, django.core.validators.MinLengthValidator(1)])),
                ('meet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swimmers', to='swimeeter_api_app.meet')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(1)])),
                ('begin_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('meet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='swimeeter_api_app.meet')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sessions', to='swimeeter_api_app.pool')),
            ],
        ),
        migrations.CreateModel(
            name='Relay_entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed_time', models.PositiveIntegerField()),
                ('heat_number', models.PositiveSmallIntegerField(null=True)),
                ('lane_number', models.PositiveSmallIntegerField(null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relay_entries', to='swimeeter_api_app.event')),
                ('swimmers', models.ManyToManyField(blank=True, related_name='relay_entries', through='swimeeter_api_app.Relay_assignment', to='swimeeter_api_app.swimmer')),
            ],
        ),
        migrations.AddField(
            model_name='relay_assignment',
            name='relay_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relay_assignments', to='swimeeter_api_app.relay_entry'),
        ),
        migrations.AddField(
            model_name='relay_assignment',
            name='swimmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relay_assignments', to='swimeeter_api_app.swimmer'),
        ),
        migrations.CreateModel(
            name='Individual_entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed_time', models.PositiveIntegerField()),
                ('heat_number', models.PositiveSmallIntegerField(null=True)),
                ('lane_number', models.PositiveSmallIntegerField(null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_entries', to='swimeeter_api_app.event')),
                ('swimmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_entries', to='swimeeter_api_app.swimmer')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='swimeeter_api_app.session'),
        ),
    ]
