# Generated by Django 4.2.2 on 2023-07-05 16:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import swimeeter_api_app.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed_time', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stroke', models.CharField(max_length=50, validators=[swimeeter_api_app.validators.event_stroke_validator])),
                ('distance', models.PositiveSmallIntegerField(validators=[swimeeter_api_app.validators.event_distance_validator])),
                ('competing_gender', models.CharField(max_length=50)),
                ('competing_max_age', models.PositiveSmallIntegerField()),
                ('competing_min_age', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Heat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_in_event', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='HeatLaneAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lane', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='Meet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lanes', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(10)])),
                ('measure_unit', models.CharField(max_length=50, validators=[swimeeter_api_app.validators.meet_measure_unit_validator])),
            ],
        ),
        migrations.CreateModel(
            name='Swimmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, validators=[swimeeter_api_app.validators.swimmer_name_validator])),
                ('last_name', models.CharField(max_length=255, validators=[swimeeter_api_app.validators.swimmer_name_validator])),
                ('age', models.PositiveSmallIntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('team', models.CharField(max_length=255)),
                ('meet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swimmers', to='swimeeter_api_app.meet')),
            ],
        ),
    ]
