# Generated by Django 4.2.2 on 2023-08-03 18:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import swimeeter_api_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('swimeeter_api_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swimmer',
            name='team_acronym',
        ),
        migrations.RemoveField(
            model_name='swimmer',
            name='team_name',
        ),
        migrations.AlterField(
            model_name='event',
            name='competing_max_age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='competing_min_age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='total_heats',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='individual_entry',
            name='heat_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='individual_entry',
            name='lane_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meet',
            name='begin_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meet',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pool',
            name='city',
            field=models.CharField(blank=True, default='', max_length=255, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='pool',
            name='country',
            field=models.CharField(blank=True, default='', max_length=255, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='pool',
            name='state',
            field=models.CharField(blank=True, default='', max_length=255, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='pool',
            name='street_address',
            field=models.CharField(blank=True, default='', max_length=255, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='pool',
            name='zipcode',
            field=models.CharField(blank=True, default='', max_length=255, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='relay_entry',
            name='heat_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='relay_entry',
            name='lane_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='swimmer',
            name='middle_initials',
            field=models.CharField(blank=True, default='', max_length=255, validators=[swimeeter_api_app.validators.swimmer_mi_validator]),
        ),
        migrations.AlterField(
            model_name='swimmer',
            name='prefix',
            field=models.CharField(blank=True, default='', max_length=255, validators=[swimeeter_api_app.validators.swimmer_ps_fix_validator]),
        ),
        migrations.AlterField(
            model_name='swimmer',
            name='suffix',
            field=models.CharField(blank=True, default='', max_length=255, validators=[swimeeter_api_app.validators.swimmer_ps_fix_validator]),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(1)])),
                ('acronym', models.CharField(max_length=255, validators=[swimeeter_api_app.validators.team_acronym_validator, django.core.validators.MinLengthValidator(1)])),
                ('meet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='swimeeter_api_app.meet')),
            ],
        ),
        migrations.AddField(
            model_name='swimmer',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='swimmers', to='swimeeter_api_app.team'),
            preserve_default=False,
        ),
    ]
