# Generated by Django 4.2.2 on 2023-07-15 02:51

import datetime
import django.core.validators
from django.db import migrations, models
import swimeeter_api_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('swimeeter_api_app', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heatlaneassignment',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='heatlaneassignment',
            name='heat',
        ),
        migrations.AddField(
            model_name='entry',
            name='heat_number',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='lane_number',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='order_in_meet',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='total_heats',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meet',
            name='begin_date',
            field=models.DateField(default=datetime.date(2023, 7, 15)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meet',
            name='end_date',
            field=models.DateField(default=datetime.date(2023, 7, 15)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meet',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='swimmer',
            name='first_name',
            field=models.CharField(max_length=255, validators=[swimeeter_api_app.validators.swimmer_name_validator, django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='swimmer',
            name='last_name',
            field=models.CharField(max_length=255, validators=[swimeeter_api_app.validators.swimmer_name_validator, django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='swimmer',
            name='team',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.DeleteModel(
            name='Heat',
        ),
        migrations.DeleteModel(
            name='HeatLaneAssignment',
        ),
    ]
