# Generated by Django 4.2.2 on 2023-08-04 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swimeeter_api_app', '0002_remove_swimmer_team_acronym_remove_swimmer_team_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swimmer',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='swimmers', to='swimeeter_api_app.team'),
        ),
    ]
