# Generated by Django 4.2.2 on 2023-08-12 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swimeeter_api_app', '0003_alter_swimmer_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='swimeeter_api_app.pool'),
        ),
        migrations.AlterField(
            model_name='swimmer',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swimmers', to='swimeeter_api_app.team'),
        ),
    ]
